### PR TITLE
#600 add another reason (robustness in sense of type safety) for LSP

### PR DESCRIPTION
**Pull request by gernotstarke**
please also add your opinion, @kraemerdr

### CODE REVIEW

**Review by alxlo — APPROVED** [review]

**Review by mikesperber — CHANGES_REQUESTED** [review]
No, this is completely wrong.

See https://github.com/isaqb-org/curriculum-foundation/issues/600#issuecomment-2416245164

**Comment by gernotstarke** [comment]
@mikesperber sorry, I see that differently: type safety is (one) approach to reduce runtime problems, and thus improve robustness (aka reduce the chance of runtime errors).

**Comment by mikesperber** [comment]
There is a confusion of terminology here:

Type safety reduces the chance of runtime *bugs* (i.e. problems in the source code *within* the software), whereas runtime errors are unforeseen circumstances at run time. Type safety does nothing to reduce those.

**Comment by gernotstarke** [comment]
that's correct, @mikesperber , but I still see "robust" as an attribute that is improved by type safety - as types might be checked both at compile- AND at runtime.

**Comment by gernotstarke** [comment]
I asked another (outside) opinion and got that result:

> IMHO the ISO 25010:2023 qualities indirectly influenced by Liskov would be faultlessness, modularity and testability.

As @danielkr did not directly answer, I close this PR without merging.

**Comment by mikesperber** [comment]
> as types might be checked both at compile- AND at runtime.

Strictly speaking, type checking is a purely compile-time mechanism. But we digress, as a "runtime type error" might also *reduce* robustness.

**Comment by kraemerdr** [comment]
> As @danielkr did not directly answer, I close this PR without merging.

@gernotstarke Because of vacation and illness, I was not able to respond earlier.

Regarding LSP, I am actually less concerned with type safety (in the sense of data structures) than with compliance to interface contracts and predictable behavior.

As mentioned in #600, there is no need to drive this discussion any further, though.

**Pull request closed without merging**
