### PR TITLE
648 lg 03 10 differentiate between cross cutting concerns and cross cutting concepts

### PR DESCRIPTION
**Pull request by gernotstarke**
hopefully the ADR-009 on concerns and concepts now works for everybody...

### CODE REVIEW

**Comment by alxlo** [comment]
I don't want to spoil the fun and overburden this ADR, but because it is heavily intertwined, we should clarify what German term to use for "concerns".  It has become quite the hot potato in its German translation. 
As far as I remember, @gernotstarke is not happy at all with the term "Belange", that @alxlo is totally fine with as that's what it was called a long time ago in my university courses. @gernotstarke prefers (IIRC) the term "Anliegen" which sounds very weird to me when it comes to "Querschnittsanliegen" and the term "Themen" is much to broad and overly general for my liking.
That's why I'm a bit surprised that in 56e7d919a5f1100f3e92bed4c3e1e67ecda7f37a  our hard won compromise to explain the usual synonyms in brackets behind that term has vanished like the single sock in washing machine.

Perhaps we could revisit this issue with fresh eyes? We could:

- Stick with one term and brace for the debate.
- Bring back the bracket approach, embracing our indecisiveness.
- Find a new term that everyone finds equally acceptable (or unacceptable).

**Comment by rhoadesre** [comment]
@Axlo: 
This is the problem that I've discussed before. The same word "Concern" is used for both "cross-cutting concerns" and "stakeholder concerns", but they have two different semantic meanings.  

For cross-cutting concerns, it's referring to a "matter for consideration". Nothing more, nothing less. 

This definition could also apply to stakeholder concerns, but for stakeholder concerns the usual description is a "marked interest or regard usually arising through a personal tie or relationship", or maybe even a "matter that causes feelings of unease, uncertainty, or apprehension". (Merriem-Webster Dictionary)

I think it's very valid to translate them differently - "Querschnittsthemen" and "Stakeholderanliegen".

**Comment by rhoadesre** [comment]
I would approve this ADR.
@Axlo: OK?

**Comment by alxlo** [comment]
Everything is fine by me, expect "Querschnittsthemen". Thema" refers to a general topic or subject, while "concern" in software architecture implies a specific area of interest or responsibility within the system. "Belang" more accurately captures this sense of importance and relevance. But if I'm the only one with this issue I'm happy to accept that. Maybe close this PR and open up an issue to talk about the translation?

**Review by rhoadesre — APPROVED** [review]
Okey Dokey. 
@Axlo: as you suggested, we'll close this PR / Issue and if want, you can create a new issue regarding the translation.

**Comment by ulibecker** [comment]
@alxlo The term Querschnittsthemen" was introduced in the German curriculum version a while ago. The issue I had was that "Querschnittskonzepte" was listed as a synonym to "Querschnittsthemen", which for me it definitely is not. @gernotstarke understandably objected to the term "aspect" due to lack of a clear definition. I am fine with "Querschnittsthemen" as well as "Querschnittsbelange".

**Pull request merged**
