### PR TITLE
#577 glossary contains references

### PR DESCRIPTION
**Pull request by gernotstarke**
@ulibecker or @skogsbaer could you please have a look... thx

### CODE REVIEW

**Review by alxlo — APPROVED** [review]

**Comment by skogsbaer** [comment]
looks good!

**Review by ulibecker — APPROVED** [review]

**Comment by alxlo** [comment]
ping @skogsbaer - From what I can see, this ADR proposal can be traced back to your [comment](https://github.com/isaqb-org/curriculum-foundation/issues/577#issuecomment-2427017319) from #577.
I would really like to merge it to keep our backlog of PRs small.  Technically merging is already possible but having feedback from you would be good.

**Review by skogsbaer — APPROVED** [review]
looks good!

**Comment by skogsbaer** [comment]
> ping @skogsbaer - From what I can see, this ADR proposal can be traced back to your [comment](https://github.com/isaqb-org/curriculum-foundation/issues/577#issuecomment-2427017319) from #577. I would really like to merge it to keep our backlog of PRs small. Technically merging is already possible but having feedback from you would be good.

I already added a positiv comment last week. I've now added my review and merged to PR.

**Pull request merged**
