### PR TITLE
first try of an ADR covering concerns and concepts

### PR DESCRIPTION
**Pull request by gernotstarke**
first try to define an ADR for concerns and concepts

### CODE REVIEW

**Review by rhoadesre — CHANGES_REQUESTED** [review]
See comments in the following issues:
#15, #299 , #396 , #539 , and most recently in #597

**Comment by gernotstarke** [comment]
@rhoadesre What is your specific proposal for this PR? 

> See comments in the following issues: #15, #299 , #396 , #539 , and most recently in #597

e.g. #597 is about quality requirements, not about concerns and concepts.

**Comment by rhoadesre** [comment]
> @rhoadesre What is your specific proposal for this PR?
> 
> > See comments in the following issues: #15, #299 , #396 , #539 , and most recently in #597
> 
> e.g. #597 is about quality requirements, not about concerns and concepts.

As far as I can tell, your ADR is about quality requirements and not cross-cutting concerns. Therefore, I made the reference to #597. My concrete proposal for changes regarding quality requirements is stated in #597. I would like to separate the ADR related to quality requirements from the changes for cross-cutting concerns.

The changes made to the curriculum for the cross-cutting concerns and concepts are good.

**Comment by gernotstarke** [comment]
oops - the wrong file made it to the change list - my fault. I make a new PR with the correct ADR... sorry for the hassle

**Pull request closed without merging**
