### PR TITLE
#313 lg 3 2 wording and relevance level issues

### PR DESCRIPTION
**Pull request by gernotstarke**
original comment: Dear reviewers, please DO NOT MERGE, but only comment... we might need to consolidate your comments or suggestions.

update Nov 20th: 2 reviewers gave "fine-by-me", so I merge

### CODE REVIEW

**Review by alxlo — COMMENTED** [review]
"die Zugänglichkeit der Dokumentation" i would translate as  "the accessibility of the documentation". But I'm not a native English speaker.

Besides that: fine by me.

**Comment by programming-wolf** [comment]
> "die Zugänglichkeit der Dokumentation" i would translate as "the accessibility of the documentation". But I'm not a native English speaker.
> 
> Besides that: fine by me.

Where do you see "Zugänglichkeit der Dokumentation" in this PR?

**Comment by programming-wolf** [comment]
Ah. It's not part of the changed lines but of the file. 

Well, your wording describes if the documentation is written accessible, for example for people who need a screen reader. 
The original wording means that everyone can access it (read: not locked behind paid accounts where only one dev has access, for example). I don't know which of the two we intend to focus on. 

But maybe I'm also reading it wrong and @rhoadesre can help :)

**Comment by gernotstarke** [comment]
@programming-wolf and @alxlo - thank you. Your "fine-by-my" is enough to merge. We should make the translation question a new issue.

See #319

**Pull request merged**
