### PR TITLE
Update Java info in README.adoc

### PR DESCRIPTION
**Pull request by alxlo**
Just found out that building the documents didn't work anymore. Updating to Java 21 fixed that for me.

### CODE REVIEW

**Comment by programming-wolf** [comment]
Java 17 is the minimum requirement.

**Comment by programming-wolf** [comment]
Also, the Readme says "up-to-date" runtime 😉

**Comment by alxlo** [comment]
> Also, the Readme says "up-to-date" runtime 😉

Yes, that's because I just added the "up-to-date" part :-)

**Comment by programming-wolf** [comment]
Oh 😆

**Review by programming-wolf — APPROVED** [review]

**Pull request merged**
