### PR TITLE
Clarify cross-cutting concerns vs. cross-cutting concepts

### LINKED ISSUE #640: LG 04-07: Cross-cutting concerns vs cross-cutting concepts
IMO cross-cutting concept and cross-cutting concerns are not synonymous:

* Cross-cutting concern corresponds to an aspect
* A solution concept for a cross-cutting concern corresponds to cross-cutting concept

### PR DESCRIPTION
**Pull request by ulibecker**
Fixes #640
Map cross-cutting concern to aspect and solution concept for a cross-cutting
concern to a cross-cutting concept

### CODE REVIEW

**Review by gernotstarke — CHANGES_REQUESTED** [review]
You introduce a new term _aspect_, which I cannot map to an existing term/concept in the curriculum. I doubt that this new term is neccessary or useful... please let us discuss that in the corresponding issue first.

**Comment by ulibecker** [comment]
The term "aspect" was already present in the curriculum: "typical cross-cutting concerns (synonym: _cross-cutting concepts_, _aspects_)..."

**Review by rhoadesre — DISMISSED** [review]
Looks good.

**Comment by rhoadesre** [comment]
Propose to corresponding changes in LG 03-10. Only the changes are referenced here. The other content remains the same.:

>explain the significance of {glossary_url}cross-cutting-concerns[cross-cutting concerns], , for example persistence, communication, GUI, error handling, concurrency, energy efficiency
>...
>design cross-cutting concepts that provide the solution approach for the corresponding cross-cutting concerns

**Review by gernotstarke — APPROVED** [review]

**Pull request merged**
