### PR TITLE
Clarify "Architekturentwurf".

### PR DESCRIPTION
**Pull request by mikesperber**
Addresses #272.

### CODE REVIEW

**Review by programming-wolf — DISMISSED** [review]
Looks good to me.

**Comment by programming-wolf** [comment]
Can this one be merged, @gernotstarke ?

**Comment by sippsack** [comment]
I'm not sure if we should drop the term "Entwurf" completely as it is a common term. I would suggest to keep "Architekturentwurf" but clarify it in the context of "Entwicklung der Architektur".

**Comment by mikesperber** [comment]
The problem with that is that the current curriculum uses the term in two different ways. I'm not averse to explaining the term, but that seems largely orthogonal to this PR.

**Comment by sippsack** [comment]
Maybe I'm a bit late to this discussion and you have already spoken about it. But in the issue I can't spot that it is used in two different ways in the curriculum. Where is it used as draft? If it is only used as "design" than it would work with clarifieng the term as I suggested and as it is initially asked for in the ticket.

**Comment by mikesperber** [comment]
> But in the issue I can't spot that it is used in two different ways in the curriculum. Where is it used as draft? If it is only used as "design" than it would work with clarifieng the term as I suggested and as it is initially asked for in the ticket.

You're probably right, as far as the curriculum itself is concerned. But see #272 for an explanation of the general issue. This suggests two remedies:

- don't use the term in the curriculum unnecessarily
- possibly mention that the term exists and has two different meanings

**Comment by alxlo** [comment]
... we should clarify both meanings in the glossary and refer from the curriculum to it.

**Review by alxlo — APPROVED** [review]
I was dangerously close to rejecting this proposal but then it clicked and I was able to see what @mikesperber did here and i think it actually is an improvement.

**Comment by alxlo** [comment]
Could someone else please approve of this as well (as some kind of sanity check) and merge it if appropriate? @gernotstarke maybe?

**Pull request merged**
