### PR TITLE
Some references for LG-{1,2,3}

### PR DESCRIPTION
**Pull request by skogsbaer**
Partially addresses #512

### CODE REVIEW

**Review by sippsack — APPROVED** [review]

**Review by programming-wolf — COMMENTED** [review]
I don't like that the references appear (sort of) randomly in the curriculum now. 
There's a dedicated references section per chapter, that should be enough. Adding the references to each paragraph clutters the curriculum, and breaks the grammar of some of them. 

I'm completely against this idea. 😢 

If you want to highlight which parts of the books you're referring to in one chapter of the curriculum, add the pages of each book in the references section.

**Comment by gernotstarke** [comment]
@programming-wolf As a foundation (and convenience) for creating and discussing LG-specific examination questions, we started adding these LG-specific references. This is part of our initiative to improve learning goals, see the appropriate section in the [readme (what consitutes good learning goals)](https://github.com/isaqb-org/curriculum-foundation#what-constitutes-good-learning-goals). 

We could discuss the current layout, though - I'm open for suggestions.

**Comment by skogsbaer** [comment]
@programming-wolf I just added some more references. There are already plenty of references in the text flow.

**Comment by programming-wolf** [comment]
Yes, that's what I don't like. Not blaming you but the concept. 😉 
Having a "References for this Learning Goal" section would be better, to my mind. 

To improve the reading flow, cleanup the text, and prevent duplicate references.

**Comment by gernotstarke** [comment]
aah - good idea imho, a (new) section "References for this LG".

If possible, could you open a PR for that, so we can try out if that looks better?

**Review by gernotstarke — APPROVED** [review]
@programming-wolf suggested to collect the references in a new section (per LG), to improve layout and readability.

Thanx @skogsbaer for your contribution.

**Comment by programming-wolf** [comment]
Yes. Once Corona is defeated, I'll do it.

**Pull request merged**
